export const colors = {
    white: '#fff',
    lightGray: '#F8F8F8',
    mediumGray: '#ededed',
    darkGray: '#484444',
    lightPink: 'lightpink',
    darkMagenta: '#2a0739',
    lightMagenta: '#7301a4',
    pink: '#ff00ca',
    deepPink: 'deeppink',
    darkPink: '#971f7e',
    fuchsia: 'fuchsia',
    lightBlue: 'lightblue',
    black: '#000',
}
